ftplugin/typescript.vim
indent/typescript.vim
syntax/typescript.vim

Hi,
I fixed a few issues I had with this plugin:
* Syntax highlighting for function definitions was broken. Type annotations completly messed up the highlighting, the used colors were inconsistent with e.g. javascript function highlighting. I simplified it by removing (just commented out for now) the special `match` rules for functions and parameters and instead simply kept the `function` keyword. Should also fix #13.
* Used `contained` on HTML element properties, ajax methods and others and used the `typeScriptDotNotation` rule for those. This used to mess up e.g. class method definitions with names like "load", "send" or "id". (Even though calling those methods will still trigger those highlighting rules – I'm not sure if they should be kept at all, but I could live with that.)
* …

Fix (simplify) function highlighting and other improvements

---

syntax/typescript.vim

Hi, I've modified syntax highlighting for the followings:
* [Template Strings](https://github.com/Microsoft/TypeScript/issues/13)
* [Decorators](https://github.com/Microsoft/TypeScript/issues/2249)
Quramy

Add syntax highlight supports for Template Strings and Decorators

---

indent/typescript.vim

The indentation function will not follow cindent practises if there is
a variable declared and the semicolon omitted on the previous line. The
indentation for the next line will be the same as the previous line.

Allow semicolon ommission on var declaration

---

syntax/typescript.vim

JSDoc comment block might be close by character `}`.
Which is end pattern of `foldBraces`.
Add `extend` to avoid this issue.
Also find another issue.
Fold setting is not set correct.
Will cause the first ts file will not have `foldBraces` rule.
And the second file will have two `foldBraces` rules.

Fix comment region closed by `}`

---

syntax/typescript.vim

This adds the following:
* Keywords: `namespace`, `from`, `of`
* Reference comments: `amd-dependency`, `amd-module`
This also adds some keywords to the correct classification.

Add missing syntax from 1.4 and 1.5

---

syntax/typescript.vim

This adds highlighting for for the ES7 `async` and `await` keywords that are in the [Roadmap for TypeScript 1.6](https://github.com/Microsoft/TypeScript/wiki/Roadmap) and currently useable in the [asyncFunctions branch](https://github.com/Microsoft/TypeScript/tree/asyncFunctions)

add ES7 async identifiers

---

ftdetect/typescript.vim

TypeScript 1.6 will include JSX support and its file extension will be `.tsx`.
The `.tsx` file is basically TypeScript code which includes XML syntax of JSX and typescript-vim should detect it.
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#new-tsx-file-extension-and-as-operator

Detect '.tsx' as TypeScript file

---

indent/typescript.vim

The current indentation uses an adaptation of Java indenting. I figured since Typescript is a superset of Javascript, the indentation should work fairly similarly. Lo and behold, it does. It works much better than the current version, and fixes problems such as #66 
Let me know what I can do to facilitate switching over.

Use adaptation of vim-javascript indentation

---

ftplugin/typescript.vim

So you can 'gf' on an import to go to that file.
``` typescript
import foo from './foo';
```
Just like `gf`, if the cursor is under `'./foo'` it will now look for a `./foo.ts` file to go to.

Add ts extension to suffixes for gf

---

ftdetect/typescript.vim

Plugins should not use setlocal filetype= while it force to overwrite existing filetype.
```
:setf[iletype] {filetype}			*:setf* *:setfiletype*
Set the 'filetype' option to {filetype}, but only if
not done yet in a sequence of (nested) autocommands.
This is short for: >
:if !did_filetype()
:  setlocal filetype={filetype}
:endif
<			This command is used in a filetype.vim file to avoid
setting the 'filetype' option twice, causing different
settings and syntax files to be loaded.
{not in Vi}
```
See [:help setfiletype](http://vimdoc.sourceforge.net/htmldoc/options.html#:setfiletype)
This cause wrong filetype assignment for example when user tried to diff content (`ft=diff`) and reassign the filetype of the content.

Use setfiletype instead of setlocal filetype=

---

indent/typescript.vim

This semicolon must be a typo; Vim script does not allow the trailing semicolon like this.

fix Fixedgq: remove invalid semicolon

---

syntax/typescript.vim

In [TypeScript 2.0](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-20), `readonly` and `never` were added as new contextual keywords.  I added them to highlight groups.

2.0 new contextual keywords

---

syntax/typescript.vim

-----
I had noticed that `'\0'` was not highlighted properly and I found unused `typescriptSpecialCharacter` prevented it from highlighting. (`typescriptSpecial` is now being used.)  I simply removed the unused highlight.

Remove unused highlight rule to fix that '\0' is not highlighted

---

syntax/typescript.vim

I just put them in with the rest of the reserved words.
See: https://www.typescriptlang.org/docs/handbook/classes.html#accessors
Fixes #88.

Support get and set keywords

---

syntax/typescript.vim

In TypeScript 2.1.x,  a new reserved word `keyof` is available. 
( https://github.com/Microsoft/TypeScript/pull/11929 )

Add "keyof" to reserved words

---

README.md
indent/typescript.vim

Update the indent script to use the indent script from pangloss/vim-javascript.

Use javascript indent

---

syntax/typescript.vim

`object` Typescript type appeared in 2.2 version: http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html.

Add 'object' Typescript type

---

ftdetect/typescript.vim

In addition to the work in #111 this puts back the ftdetect for *.tsx but uses `setfiletype` to avoid overwriting the filetype set by any other plugins.

Add back *.tsx file detection

---

ftplugin/typescript.vim

* gf worked with '.ts' but not React's '.tsx'. This remedies that.

Add 'gf' to '.tsx' files

---

syntax/typescript.vim

TypeScript supports binary literal (`0b`) and octal literal (`0o`).
Rel: https://www.typescriptlang.org/docs/handbook/basic-types.html
```typescript
var b = 0b110101011001;
console.log(b);
b = 0o1234567;
console.log(b);
```
I added support for them.

Binary and octal literals

---

syntax/typescript.vim

ECMAScript numeric separator proposal is now on stage3
https://github.com/tc39/proposal-numeric-separator
and will come to TypeScript at version 2.7.
https://github.com/Microsoft/TypeScript/pull/20324
Example:
```typescript
const i = 123_456;
const x = 0x1fa_EF6;
const f = 123_456.0_456;
const f2 = 123_456.4_5e1_2;
```
I added syntax highlight support for this feature. I confirmed it works on my machine:

Support numeric separator (i.e. 123_456)

---

syntax/typescript.vim

I previously added support for octal and binary int literals at #130. However, I noticed that I had broken decimal integer literal at ba0d89cb4d90f004ea47e087064f8ed3fd242619.
So I fixed it in this PR.

Fix integer literal

---

syntax/typescript.vim

unknown type is added since TypeScript 3.
https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#the-unknown-type

Highlight unknown as typescriptType

---

syntax/typescript.vim

Unicode codepoint notations like `\x00A5` or `\20` or `\x0a` are not highlighted in string literal. I fixed them in this PR as follows:
- Current
- By this PR

Fix code points notation in string literals

---

syntax/typescript.vim

It was missing from the `typescriptLogicSymbols` class, where I
think it belongs.
@leafgarland could you take a look please :eyes: ?

Adding ! as logical operator

---

syntax/typescript.vim

`JSON` was missing from `typescriptGlobalObjects`.
@leafgarland can you take a look at this one too please :eyeglasses: ?

Adding JSON as global object.

---

README.md

Added working installation command-line for Windows/Powershell, with two changes compared to the Unix one: install to 'vimfiles' instead of '.vim' and use '$home' for the root directory instead of '~'. Tested with vanilla Vim 8.1 downloaded from https://www.vim.org.

Updated installation instructions to working command line for Powershell

---

syntax/typescript.vim

The "function" keyword is not, itself, a Function. It is a Keyword. This pull request solves the problem once and for all.
It also cleans up some unnecessary trailing whitespace in the first commit.

Fix typescript func keyword

---

indent/typescript.vim

Simple fix. Now paired '<>' close like (), {}, and []. Eg:
```typescript
const myFunction = <
GenericA,
GenericB,
GenericC
>(a: GenericA, b: GenericB, c:GenericC): GenericA => {
return a
}
```
It seems to work correctly for edge cases that I've tested.

Add closing '>' to containing groups

---

syntax/typescript.vim

I noticed some syntax highlighting issues with recent versions of vim:
Normal keywords like `import` and `from` are now highlighted red. 
For reference, here are links to the relevant lines in [`$VIMRUNTIME/syntax/typescriptcommon.vim`](https://github.com/vim/vim/blob/559b9c68fe550f3af63d42e0838622aab1ceb1b3/runtime/syntax/typescriptcommon.vim#L1950) and [`[typescript-vim]/syntax/typescript.vim`](https://github.com/leafgarland/typescript-vim/blob/5a319ea5504e18215d155576c78d1b7fb8e22c8f/syntax/typescript.vim#L278)
Running `:hi typescriptReserved` reports `typescriptReserved xxx links to Error`. 
Vim has recently added built-in support for typescript. Vim's built-in syntax script is linking `typescriptReserved` to `Error`. This prevents typescript-vim from linking it to Keyword because …

Compatibility with latest vim

---

syntax/typescript.vim

This change adds known _javascript_ and _Node JS_ keywords and objects to the keyword list.
- Extend definition `typescriptGlobalObjects` with keywords (including `Map`, `Promise`, `console`, `document`, `fetch`, and  `window`, among others).
- Add new definition `typescriptGlobalNodeObjects` with keywords specific to Node JS.
- Update the `typescriptAll` cluster to include the new `typescriptGlobalNodeObjects` definition.
- Link the new `typescriptGlobalNodeObjects` definition to the `Special` highlight group.
Hi 👋 My name is Patrick. First time contributor, happy to answer questions, let me know if you have feedback. Thanks!

Extend global objects definition with js and node keywords

---

syntax/typescript.vim

The exclamation character is considered as a `typescriptLogicSymbols` when in a `!==`, which breaks some fonts due to the color change.
With this line exchange, the exclamation is interpreted as it should be (`typescriptOpSymbols`)
*Before the change:*
*After the change:*

exclamation character wrong group

---

syntax/typescript.vim

This version of neovim has the same typescript support as vim 8
patch-8.1.1486, so we should override it as well.

Override neovim 0.5.0 and up's typescript support

---

syntax/typescript.vim

Implements the suggestion posted in:
- https://github.com/leafgarland/typescript-vim/pull/193#issuecomment-1751705278
Which aligns the plugin with what other popular plugins that override bundled syntax files do. eg.
- [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown) (uses `hi def link` on version 508 and above)
- [tpope/vim-markdown](https://github.com/tpope/vim-markdown) (uses `hi def link` unconditionally)
This stops highlighting from getting obliterated when activating a colorscheme that uses `:hi clear` (which will reset highlights back to defaults), such as [a Base16 theme](https://github.com/chriskempson/base16-vim/blob/3be3cd82cd31acfcab9a41bad853d9c68d30478d/colors/base16-one-light.vim#L146) or [Dracula](https://github.com/dracula/vim/blob/b2cc39273abbb6b38a3d …

fix: prefer default links except on ancient Vim versions
